export const industryOptions = [
    { value: "business_services", label: "Business Services" },
    {
        value: "energy_and_natural_resources",
        label: "Energy & Natural Resources",
    },
    { value: "financial_services", label: "Financial Services" },
    { value: "fmcg", label: "FMCG (Fast Moving Consumer Goods)" },
    { value: "healthcare", label: "Healthcare" },
    { value: "industrial_manufacturing", label: "Industrial / Manufacturing" },
    { value: "insurance", label: "Industrial / Manufacturing" },
    { value: "leisure_travel_tourism", label: "Leisure, Travel & Tourism" },
    { value: "life_science", label: "Life Science" },
    { value: "media_and_agency", label: "Media & Agency" },
    { value: "not_for_profit", label: "Not For Profit" },
    { value: "professional_services", label: "Professional Services" },
    { value: "property", label: "Property" },
    { value: "public_sector", label: "Public Sector" },
    { value: "retail", label: "Retail" },
    { value: "technology_and_telecoms", label: "Technology & Telecoms" },
    { value: "transport_and_distribution", label: "Transport & Distribution" },
];

export const sectorOptions = [
    { value: "accounting", label: "Accounting" },
    { value: "audit_and_advisory", label: "Audit & Advisory" },
    { value: "banking_and_financial_services", label: "Banking & Financial Services" },
    { value: "construction", label: "Construction" },
    { value: "engineering_and_manufacturing", label: "Engineering & Manufacturing" },
    { value: "facilities_and_management", label: "Facilities Management" },
    { value: "human_resources", label: "Human Resources" },
    { value: "human_resources", label: "Human Resources" },
    { value: "information_technology", label: "Information Technology" },
    { value: "legal", label: "Legal" },
    { value: "life_sciences", label: "Life Sciences" },
    { value: "marketing", label: "Marketing" },
    { value: "office_support", label: "Office Support" },
    { value: "oil_and_gas", label: "Oil & Gas" },
    { value: "procurement_and_supply_chain", label: "Procurement & Supply Chain" },
    { value: "real_estate", label: "Real Estate" },
    { value: "renewable_energy", label: "Renewable Energy" },
    { value: "sales", label: "Sales" },
    { value: "tax", label: "Tax" },
    { value: "treasury", label: "Treasury" }
]